### ISSUE TITLE
fix inactive links in the head section of the website template when setting heilmeier_catechism: true

### ISSUE THREAD

**Issue by NiklasTR** [labdao/project-theme#1]
I modified the project theme such that when ```heilmeier catechism``` is set to true, a set of top links are available in the navigation bar: 

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/18559148/197191613-453be2d3-5a27-4c95-8556-76461aafffa7.png">

My next step was to change the links in 
https://github.com/labdao/project-theme/blob/master/_layouts/default.html line 26+ such that they link to the various subpages (for example "Team" should map to "team.md"). 

I am stuck with the mapping of the names however. Can you open a pull request that changes the links within _layouts/default.html line 26+ such that they link to the respective subpages?

**Comment by jlevers** [comment]
@NiklasTR this is fixed. The way it's fixed right now assumes you're not adding permalinks to the front matter for each page, so if you create `about.md` it'll be rendered to `/about.html`. If you'd rather have it render to a path like `/about`, you can add a `permalink` attribute in the front matter for the page, like I've done here for `another-page.md`:

https://github.com/labdao/project-theme/blob/a17d5a221b85e4561a71c092109bf919093dc1b8/another-page.md?plain=1#L1-L6

That makes it so that `another-page.md` is rendered to `/another-page`
